import type { RealClub } from "./worldCountries.ts";

// International Soccer Zen GM mod (Epic 7): the real teams the USA's top tier
// is made of (see chooseRealClubs), decided with the user: mostly real pro,
// minor league, and college teams from any sport. Logos are copied from
// Wikipedia into public/img/world-logos/usa/, and colors are taken from them.
// Towns are from AMERICAN_TOWNS, for each club's market size and team page.

const logo = (file: string) => `/img/world-logos/usa/${file}`;

export const AMERICAN_REAL_CLUBS: RealClub[] = [
	// The user's teams, picked first when a top tier has fewer than 20 clubs
	{
		region: "Seattle",
		name: "SuperSonics",
		abbrev: "SEA",
		town: "Seattle",
		colors: ["#005831", "#ffc121", "#ffffff"],
		imgURL: logo("seattle-supersonics.svg"),
		pickFirst: true,
	},
	{
		region: "Portland",
		name: "Beavers",
		abbrev: "POR",
		town: "Portland",
		colors: ["#002255", "#6699cc", "#ffffff"],
		imgURL: logo("portland-beavers.png"),
		pickFirst: true,
	},
	{
		region: "Oakland",
		name: "Raiders",
		abbrev: "OAK",
		town: "Oakland",
		colors: ["#000000", "#a5acaf", "#ffffff"],
		imgURL: logo("oakland-raiders.svg"),
		pickFirst: true,
	},
	{
		region: "San Francisco",
		name: "Seals",
		abbrev: "SFS",
		town: "San Francisco",
		colors: ["#222222", "#ffffff", "#999999"],
		imgURL: logo("san-francisco-seals.png"),
		pickFirst: true,
	},
	{
		region: "Sacramento",
		name: "Solons",
		abbrev: "SAC",
		town: "Sacramento",
		colors: ["#cc2244", "#ffffff", "#1c2c5b"],
		imgURL: logo("sacramento-solons.png"),
		pickFirst: true,
	},
	{
		region: "Fresno",
		name: "Bulldogs",
		abbrev: "FRE",
		town: "Fresno",
		colors: ["#c41230", "#13284c", "#ffffff"],
		imgURL: logo("fresno-bulldogs.svg"),
		pickFirst: true,
	},
	{
		region: "Brooklyn",
		name: "Dodgers",
		abbrev: "BKN",
		town: "New York City",
		colors: ["#113388", "#ffffff", "#dd1133"],
		imgURL: logo("brooklyn-dodgers.png"),
		pickFirst: true,
	},
	{
		region: "San Diego",
		name: "Aztecs",
		abbrev: "SDA",
		town: "San Diego",
		colors: ["#c41230", "#000000", "#ffffff"],
		imgURL: logo("san-diego-aztecs.svg"),
		pickFirst: true,
	},
	{
		region: "Dallas",
		name: "Cowboys",
		abbrev: "DAL",
		town: "Dallas",
		colors: ["#002244", "#869397", "#ffffff"],
		imgURL: logo("dallas-cowboys.svg"),
		pickFirst: true,
	},
	{
		region: "Pittsburgh",
		name: "Steelers",
		abbrev: "PIT",
		town: "Pittsburgh",
		colors: ["#101820", "#ffb612", "#ffffff"],
		imgURL: logo("pittsburgh-steelers.svg"),
		pickFirst: true,
	},
	{
		region: "New Orleans",
		name: "Jazz",
		abbrev: "NOJ",
		town: "New Orleans",
		colors: ["#552266", "#ffffff", "#fdb927"],
		imgURL: logo("new-orleans-jazz.png"),
		pickFirst: true,
	},
	{
		region: "Miami",
		name: "Hurricanes",
		abbrev: "MIA",
		town: "Miami",
		colors: ["#f47321", "#005030", "#ffffff"],
		imgURL: logo("miami-hurricanes.svg"),
		pickFirst: true,
	},
	{
		region: "New York",
		name: "Yankees",
		abbrev: "NYY",
		town: "New York City",
		colors: ["#0c2340", "#ffffff", "#c4ced3"],
		imgURL: logo("new-york-yankees.svg"),
		pickFirst: true,
	},

	// The rest the user chose, to fill a top tier of up to 20
	{
		region: "New York",
		name: "Knickerbockers",
		abbrev: "NYK",
		town: "New York City",
		colors: ["#1d428a", "#f58426", "#ffffff"],
		imgURL: logo("new-york-knickerbockers.svg"),
		pickFirst: false,
	},
	{
		// After UCLA
		region: "Los Angeles",
		name: "Bruins",
		abbrev: "LAB",
		town: "Los Angeles",
		colors: ["#2774ae", "#ffd100", "#ffffff"],
		imgURL: logo("los-angeles-bruins.svg"),
		pickFirst: false,
	},
	{
		region: "Houston",
		name: "Oilers",
		abbrev: "HOU",
		town: "Houston",
		colors: ["#4b92db", "#cc0022", "#ffffff"],
		imgURL: logo("houston-oilers.png"),
		pickFirst: false,
	},
	{
		region: "Detroit",
		name: "Tigers",
		abbrev: "DET",
		town: "Detroit",
		colors: ["#0c2c56", "#fa4616", "#ffffff"],
		imgURL: logo("detroit-tigers.svg"),
		pickFirst: false,
	},
	{
		region: "Chicago",
		name: "Bears",
		abbrev: "CHI",
		town: "Chicago",
		colors: ["#0b162a", "#e64100", "#ffffff"],
		imgURL: logo("chicago-bears.svg"),
		pickFirst: false,
	},
	{
		region: "Philadelphia",
		name: "Phillies",
		abbrev: "PHI",
		town: "Philadelphia",
		colors: ["#c81e3b", "#013b73", "#ffffff"],
		imgURL: logo("philadelphia-phillies.svg"),
		pickFirst: false,
	},
	{
		region: "Boston",
		name: "Celtics",
		abbrev: "BOS",
		town: "Boston",
		colors: ["#008248", "#ba9653", "#ffffff"],
		imgURL: logo("boston-celtics.svg"),
		pickFirst: false,
	},
];
