import type { RealClub } from "./worldCountries.ts";

// International Soccer Zen GM mod (Epic 7): the USA's real clubs, decided with
// the user: real pro, minor league, and college teams from any sport, in all
// three tiers. Clubs are named for cities, never states or schools, and a
// college team can play in a bigger city near its campus ("Oklahoma City
// Sooners"). Logos are copied from Wikipedia into public/img/world-logos/usa/.
// Towns are from AMERICAN_TOWNS, for each club's market size and team page.

const logo = (file: string) => `/img/world-logos/usa/${file}`;

const club = (
	region: string,
	name: string,
	abbrev: string,
	town: string,
	colors: RealClub["colors"],
	file: string,
	pickFirst?: true,
): RealClub => ({
	region,
	name,
	abbrev,
	town,
	colors,
	imgURL: logo(file),
	...(pickFirst ? { pickFirst } : {}),
});

// The user's teams (pickFirst), picked before the rest when the top tier has
// fewer than 20 clubs
const TOP_TIER: RealClub[] = [
	club(
		"Seattle",
		"SuperSonics",
		"SEA",
		"Seattle",
		["#005831", "#ffc121", "#ffffff"],
		"seattle-supersonics.svg",
		true,
	),
	// Oregon State's beaver, so it isn't a baseball logo
	club(
		"Portland",
		"Beavers",
		"POR",
		"Portland",
		["#dc4405", "#000000", "#ffffff"],
		"portland-beavers.svg",
		true,
	),
	club(
		"Oakland",
		"Raiders",
		"OAK",
		"Oakland",
		["#000000", "#a5acaf", "#ffffff"],
		"oakland-raiders.svg",
		true,
	),
	club(
		"San Francisco",
		"Seals",
		"SFS",
		"San Francisco",
		["#222222", "#ffffff", "#999999"],
		"san-francisco-seals.png",
		true,
	),
	club(
		"Sacramento",
		"Solons",
		"SAC",
		"Sacramento",
		["#cc2244", "#ffffff", "#1c2c5b"],
		"sacramento-solons.png",
		true,
	),
	club(
		"Fresno",
		"Bulldogs",
		"FRE",
		"Fresno",
		["#c41230", "#13284c", "#ffffff"],
		"fresno-bulldogs.svg",
		true,
	),
	// The "B" cap logo
	club(
		"Brooklyn",
		"Dodgers",
		"BKN",
		"New York City",
		["#113388", "#ffffff", "#dd1133"],
		"brooklyn-dodgers.svg",
		true,
	),
	club(
		"San Diego",
		"Aztecs",
		"SDA",
		"San Diego",
		["#c41230", "#000000", "#ffffff"],
		"san-diego-aztecs.svg",
		true,
	),
	club(
		"Dallas",
		"Cowboys",
		"DAL",
		"Dallas",
		["#002244", "#869397", "#ffffff"],
		"dallas-cowboys.svg",
		true,
	),
	club(
		"Pittsburgh",
		"Steelers",
		"PIT",
		"Pittsburgh",
		["#101820", "#ffb612", "#ffffff"],
		"pittsburgh-steelers.svg",
		true,
	),
	club(
		"New Orleans",
		"Jazz",
		"NOJ",
		"New Orleans",
		["#552266", "#ffffff", "#fdb927"],
		"new-orleans-jazz.png",
		true,
	),
	// An "M" logo, Miami University's RedHawks
	club(
		"Miami",
		"Hurricanes",
		"MIA",
		"Miami",
		["#f47321", "#005030", "#ffffff"],
		"miami-hurricanes.svg",
		true,
	),
	// The interlocking "NY" cap logo
	club(
		"New York",
		"Yankees",
		"NYY",
		"New York City",
		["#0c2340", "#ffffff", "#c4ced3"],
		"new-york-yankees.svg",
		true,
	),
	club(
		"New York",
		"Knickerbockers",
		"NYK",
		"New York City",
		["#1d428a", "#f58426", "#ffffff"],
		"new-york-knickerbockers.svg",
	),
	// After UCLA
	club(
		"Los Angeles",
		"Bruins",
		"LAB",
		"Los Angeles",
		["#2774ae", "#ffd100", "#ffffff"],
		"los-angeles-bruins.svg",
	),
	club(
		"Houston",
		"Oilers",
		"HOU",
		"Houston",
		["#4b92db", "#cc0022", "#ffffff"],
		"houston-oilers.png",
	),
	club(
		"Detroit",
		"Tigers",
		"DET",
		"Detroit",
		["#0c2c56", "#fa4616", "#ffffff"],
		"detroit-tigers.svg",
	),
	club(
		"Chicago",
		"Bears",
		"CHI",
		"Chicago",
		["#0b162a", "#e64100", "#ffffff"],
		"chicago-bears.svg",
	),
	club(
		"Philadelphia",
		"Phillies",
		"PHI",
		"Philadelphia",
		["#c81e3b", "#013b73", "#ffffff"],
		"philadelphia-phillies.svg",
	),
	club(
		"Boston",
		"Celtics",
		"BOS",
		"Boston",
		["#008248", "#ba9653", "#ffffff"],
		"boston-celtics.svg",
	),
];

// College teams are after the schools (Oklahoma Sooners, Texas Longhorns, and so
// on), in cities near them
const SECOND_TIER: RealClub[] = [
	club(
		"Oklahoma City",
		"Sooners",
		"OKC",
		"Oklahoma City",
		["#841617", "#fdf9d8", "#ffffff"],
		"oklahoma-city-sooners.svg",
	),
	club(
		"Austin",
		"Longhorns",
		"AUS",
		"Austin",
		["#bf5700", "#ffffff", "#333f48"],
		"austin-longhorns.svg",
	),
	club(
		"Birmingham",
		"Crimson Tide",
		"BIR",
		"Birmingham",
		["#9e1b32", "#ffffff", "#828a8f"],
		"birmingham-crimson-tide.svg",
	),
	club(
		"Detroit",
		"Wolverines",
		"DTW",
		"Detroit",
		["#00274c", "#ffcb05", "#ffffff"],
		"detroit-wolverines.svg",
	),
	club(
		"Columbus",
		"Buckeyes",
		"CLB",
		"Columbus",
		["#bb0000", "#666666", "#ffffff"],
		"columbus-buckeyes.svg",
	),
	club(
		"Chicago",
		"Fighting Irish",
		"CFI",
		"Chicago",
		["#0c2340", "#c99700", "#ffffff"],
		"chicago-fighting-irish.svg",
	),
	club(
		"Los Angeles",
		"Trojans",
		"LAT",
		"Los Angeles",
		["#990000", "#ffcc00", "#ffffff"],
		"los-angeles-trojans.svg",
	),
	club(
		"Jacksonville",
		"Gators",
		"JAX",
		"Jacksonville",
		["#0021a5", "#fa4616", "#ffffff"],
		"jacksonville-gators.svg",
	),
	club(
		"Baton Rouge",
		"Tigers",
		"BTR",
		"Baton Rouge",
		["#461d7c", "#fdd023", "#ffffff"],
		"baton-rouge-tigers.svg",
	),
	club(
		"Louisville",
		"Wildcats",
		"LOU",
		"Louisville",
		["#0033a0", "#ffffff", "#000000"],
		"louisville-wildcats.svg",
	),
	club(
		"Raleigh",
		"Blue Devils",
		"RAL",
		"Raleigh",
		["#003087", "#ffffff", "#000000"],
		"raleigh-blue-devils.svg",
	),
	club(
		"Charlotte",
		"Tar Heels",
		"CHA",
		"Charlotte",
		["#7bafd4", "#ffffff", "#13294b"],
		"charlotte-tar-heels.svg",
	),
	club(
		"Kansas City",
		"Chiefs",
		"KCC",
		"Kansas City",
		["#e31837", "#ffb81c", "#ffffff"],
		"kansas-city-chiefs.svg",
	),
	club(
		"St. Louis",
		"Cardinals",
		"STL",
		"St. Louis",
		["#c41e3a", "#0c2340", "#fedb00"],
		"st-louis-cardinals.svg",
	),
	club(
		"Green Bay",
		"Packers",
		"GBP",
		"Green Bay",
		["#203731", "#ffb612", "#ffffff"],
		"green-bay-packers.svg",
	),
	club(
		"Denver",
		"Broncos",
		"DEN",
		"Denver",
		["#fb4f14", "#002244", "#ffffff"],
		"denver-broncos.svg",
	),
	club(
		"Cleveland",
		"Browns",
		"CLE",
		"Cleveland",
		["#311d00", "#ff3c00", "#ffffff"],
		"cleveland-browns.svg",
	),
	club(
		"Baltimore",
		"Orioles",
		"BAL",
		"Baltimore",
		["#df4601", "#000000", "#ffffff"],
		"baltimore-orioles.svg",
	),
	club(
		"Milwaukee",
		"Bucks",
		"MIL",
		"Milwaukee",
		["#00471b", "#eee1c6", "#0077c0"],
		"milwaukee-bucks.svg",
	),
	club(
		"Hartford",
		"Whalers",
		"HFD",
		"Hartford",
		["#00754a", "#162d53", "#ffffff"],
		"hartford-whalers.svg",
	),
];

const THIRD_TIER: RealClub[] = [
	club(
		"Portland",
		"Ducks",
		"PDX",
		"Portland",
		["#154733", "#fee123", "#ffffff"],
		"portland-ducks.svg",
	),
	club(
		"Omaha",
		"Cornhuskers",
		"OMA",
		"Omaha",
		["#e41c38", "#ffffff", "#000000"],
		"omaha-cornhuskers.svg",
	),
	club(
		"Philadelphia",
		"Nittany Lions",
		"PNL",
		"Philadelphia",
		["#041e42", "#ffffff", "#96bee6"],
		"philadelphia-nittany-lions.svg",
	),
	club(
		"Atlanta",
		"Bulldogs",
		"ATL",
		"Atlanta",
		["#ba0c2f", "#000000", "#ffffff"],
		"atlanta-bulldogs.svg",
	),
	club(
		"Richmond",
		"Hokies",
		"RIC",
		"Richmond",
		["#630031", "#cf4420", "#ffffff"],
		"richmond-hokies.svg",
	),
	club(
		"Wichita",
		"Jayhawks",
		"WIC",
		"Wichita",
		["#0051ba", "#e8000d", "#ffc82d"],
		"wichita-jayhawks.svg",
	),
	club(
		"Indianapolis",
		"Hoosiers",
		"IND",
		"Indianapolis",
		["#990000", "#ffffff", "#000000"],
		"indianapolis-hoosiers.svg",
	),
	club(
		"Phoenix",
		"Sun Devils",
		"PHX",
		"Phoenix",
		["#8c1d40", "#ffc627", "#ffffff"],
		"phoenix-sun-devils.svg",
	),
	club(
		"Salt Lake City",
		"Utes",
		"SLU",
		"Salt Lake City",
		["#cc0000", "#ffffff", "#000000"],
		"salt-lake-city-utes.svg",
	),
	club(
		"Salt Lake City",
		"Cougars",
		"SLC",
		"Salt Lake City",
		["#002e5d", "#ffffff", "#0062b8"],
		"salt-lake-city-cougars.png",
	),
	club(
		"Madison",
		"Badgers",
		"MAD",
		"Madison",
		["#c5050c", "#ffffff", "#000000"],
		"madison-badgers.svg",
	),
	club(
		"Des Moines",
		"Hawkeyes",
		"DSM",
		"Des Moines",
		["#ffcd00", "#000000", "#ffffff"],
		"des-moines-hawkeyes.svg",
	),
	club(
		"Nashville",
		"Volunteers",
		"NSH",
		"Nashville",
		["#ff8200", "#ffffff", "#58595b"],
		"nashville-volunteers.svg",
	),
	club(
		"San Antonio",
		"Aggies",
		"SAT",
		"San Antonio",
		["#500000", "#ffffff", "#998542"],
		"san-antonio-aggies.png",
	),
	club(
		"Syracuse",
		"Orange",
		"SYR",
		"Syracuse",
		["#f76900", "#000e54", "#ffffff"],
		"syracuse-orange.svg",
	),
	club(
		"Little Rock",
		"Razorbacks",
		"LRK",
		"Little Rock",
		["#9d2235", "#ffffff", "#000000"],
		"little-rock-razorbacks.png",
	),
	club(
		"Boise",
		"Broncos",
		"BOI",
		"Boise",
		["#0033a0", "#d64309", "#ffffff"],
		"boise-broncos.svg",
	),
	club(
		"Colorado Springs",
		"Buffaloes",
		"COS",
		"Colorado Springs",
		["#000000", "#cfb87c", "#ffffff"],
		"colorado-springs-buffaloes.svg",
	),
	club(
		"Honolulu",
		"Rainbow Warriors",
		"HON",
		"Honolulu",
		["#024731", "#ffffff", "#000000"],
		"honolulu-rainbow-warriors.svg",
	),
	club(
		"Cincinnati",
		"Reds",
		"CIN",
		"Cincinnati",
		["#c6011f", "#ffffff", "#000000"],
		"cincinnati-reds.svg",
	),
];

export const AMERICAN_CLUBS_BY_TIER: RealClub[][] = [
	TOP_TIER,
	SECOND_TIER,
	THIRD_TIER,
];
