import type { RealClub } from "./worldCountries.ts";

// International Soccer Zen GM mod (Epic 7): the United Kingdom's real clubs,
// decided with the user: English, Scottish, Welsh, and Northern Irish clubs in
// one pyramid. Each tier's clubs start roughly at their real standing (the
// 2025-26 Premier League, plus Celtic and Rangers, on top), in rough order of
// stature, so a smaller Division keeps the clubs at the top of its list. Crests
// are copied from Wikipedia into public/img/world-logos/uk/. Towns are from
// BRITISH_TOWNS.

const crest = (file: string) => `/img/world-logos/uk/${file}`;

const club = (
	region: string,
	name: string,
	abbrev: string,
	town: string,
	colors: RealClub["colors"],
	file: string,
): RealClub => ({ region, name, abbrev, town, colors, imgURL: crest(file) });

export const BRITISH_CLUBS_BY_TIER: RealClub[][] = [
	[
		club(
			"Manchester",
			"United",
			"MUN",
			"Manchester",
			["#da291c", "#ffffff", "#000000"],
			"manchester-united.svg",
		),
		club(
			"Liverpool",
			"FC",
			"LIV",
			"Liverpool",
			["#c8102e", "#ffffff", "#00b2a9"],
			"liverpool.png",
		),
		club(
			"Arsenal",
			"FC",
			"ARS",
			"London",
			["#ef0107", "#ffffff", "#023474"],
			"arsenal.svg",
		),
		club(
			"Chelsea",
			"FC",
			"CHE",
			"London",
			["#034694", "#ffffff", "#dba111"],
			"chelsea.svg",
		),
		club(
			"Manchester",
			"City",
			"MCI",
			"Manchester",
			["#6cabdd", "#ffffff", "#1c2c5b"],
			"manchester-city.svg",
		),
		club(
			"Tottenham",
			"Hotspur",
			"TOT",
			"London",
			["#ffffff", "#132257", "#132257"],
			"tottenham-hotspur.svg",
		),
		club(
			"Celtic",
			"FC",
			"CEL",
			"Glasgow",
			["#018749", "#ffffff", "#000000"],
			"celtic.svg",
		),
		club(
			"Rangers",
			"FC",
			"RAN",
			"Glasgow",
			["#1b458f", "#ffffff", "#c8102e"],
			"rangers.svg",
		),
		club(
			"Newcastle",
			"United",
			"NEW",
			"Newcastle upon Tyne",
			["#241f20", "#ffffff", "#41b6e6"],
			"newcastle-united.svg",
		),
		club(
			"Aston",
			"Villa",
			"AVL",
			"Birmingham",
			["#670e36", "#95bfe5", "#ffffff"],
			"aston-villa.svg",
		),
		club(
			"West Ham",
			"United",
			"WHU",
			"London",
			["#7a263a", "#1bb1e7", "#ffffff"],
			"west-ham-united.svg",
		),
		club(
			"Everton",
			"FC",
			"EVE",
			"Liverpool",
			["#003399", "#ffffff", "#000000"],
			"everton.svg",
		),
		club(
			"Brighton & Hove",
			"Albion",
			"BHA",
			"Brighton",
			["#0057b8", "#ffffff", "#ffcd00"],
			"brighton-and-hove-albion.svg",
		),
		club(
			"Nottingham",
			"Forest",
			"NFO",
			"Nottingham",
			["#dd0000", "#ffffff", "#000000"],
			"nottingham-forest.svg",
		),
		club(
			"Crystal",
			"Palace",
			"CRY",
			"London",
			["#1b458f", "#c4122e", "#ffffff"],
			"crystal-palace.svg",
		),
		club(
			"Wolverhampton",
			"Wanderers",
			"WOL",
			"Wolverhampton",
			["#fdb913", "#231f20", "#ffffff"],
			"wolverhampton-wanderers.svg",
		),
		club(
			"Fulham",
			"FC",
			"FUL",
			"London",
			["#ffffff", "#000000", "#cc0000"],
			"fulham.svg",
		),
		club(
			"Brentford",
			"FC",
			"BRE",
			"London",
			["#e30613", "#ffffff", "#000000"],
			"brentford.svg",
		),
		club(
			"AFC",
			"Bournemouth",
			"BOU",
			"Bournemouth",
			["#da291c", "#000000", "#ffffff"],
			"bournemouth.svg",
		),
		club(
			"Leeds",
			"United",
			"LEE",
			"Leeds",
			["#ffffff", "#1d428a", "#ffcd00"],
			"leeds-united.svg",
		),
	],
	[
		club(
			"Sunderland",
			"AFC",
			"SUN",
			"Sunderland",
			["#eb172b", "#ffffff", "#000000"],
			"sunderland.svg",
		),
		club(
			"Leicester",
			"City",
			"LEI",
			"Leicester",
			["#003090", "#fdbe11", "#ffffff"],
			"leicester-city.svg",
		),
		club(
			"Southampton",
			"FC",
			"SOU",
			"Southampton",
			["#d71920", "#ffffff", "#000000"],
			"southampton.svg",
		),
		club(
			"Burnley",
			"FC",
			"BUR",
			"Burnley",
			["#6c1d45", "#99d6ea", "#ffffff"],
			"burnley.svg",
		),
		club(
			"Ipswich",
			"Town",
			"IPS",
			"Ipswich",
			["#3a64a3", "#ffffff", "#de2c37"],
			"ipswich-town.svg",
		),
		club(
			"Sheffield",
			"United",
			"SHU",
			"Sheffield",
			["#ee2737", "#ffffff", "#000000"],
			"sheffield-united.svg",
		),
		club(
			"Middlesbrough",
			"FC",
			"MID",
			"Middlesbrough",
			["#e11b22", "#ffffff", "#000000"],
			"middlesbrough.svg",
		),
		club(
			"West Bromwich",
			"Albion",
			"WBA",
			"West Bromwich",
			["#122f67", "#ffffff", "#000000"],
			"west-bromwich-albion.svg",
		),
		club(
			"Norwich",
			"City",
			"NOR",
			"Norwich",
			["#fff200", "#00a650", "#ffffff"],
			"norwich-city.svg",
		),
		club(
			"Cardiff",
			"City",
			"CAR",
			"Cardiff",
			["#0070b5", "#ffffff", "#d11524"],
			"cardiff-city.svg",
		),
		club(
			"Swansea",
			"City",
			"SWA",
			"Swansea",
			["#ffffff", "#000000", "#121212"],
			"swansea-city.svg",
		),
		club(
			"Wrexham",
			"AFC",
			"WRE",
			"Wrexham",
			["#d71920", "#ffffff", "#1c2c5b"],
			"wrexham.svg",
		),
		club(
			"Coventry",
			"City",
			"COV",
			"Coventry",
			["#6cabdd", "#ffffff", "#1c2c5b"],
			"coventry-city.svg",
		),
		club(
			"Stoke",
			"City",
			"STK",
			"Stoke-on-Trent",
			["#e03a3e", "#ffffff", "#1b449c"],
			"stoke-city.svg",
		),
		club(
			"Aberdeen",
			"FC",
			"ABE",
			"Aberdeen",
			["#e2001a", "#ffffff", "#000000"],
			"aberdeen.svg",
		),
		club(
			"Derby",
			"County",
			"DER",
			"Derby",
			["#ffffff", "#000000", "#b3995d"],
			"derby-county.svg",
		),
		club(
			"Hull",
			"City",
			"HUL",
			"Kingston upon Hull",
			["#f5971d", "#000000", "#ffffff"],
			"hull-city.svg",
		),
		club(
			"Watford",
			"FC",
			"WAT",
			"Watford",
			["#fbee23", "#ed2127", "#000000"],
			"watford.svg",
		),
		club(
			"Linfield",
			"FC",
			"LIN",
			"Belfast",
			["#0033a0", "#ffffff", "#c8102e"],
			"linfield.svg",
		),
		club(
			"Glentoran",
			"FC",
			"GLE",
			"Belfast",
			["#00843d", "#000000", "#c8102e"],
			"glentoran.svg",
		),
	],
];
