import type { RealClub } from "./worldCountries.ts";

// International Soccer Zen GM mod (Epic 7): Germany's real clubs, decided with
// the user. Each tier's clubs start roughly at their real standing (the 2025-26
// Bundesliga on top, 2. Bundesliga below), in rough order of stature, so a
// smaller Division keeps the clubs at the top of its list. Crests are copied
// from Wikipedia into public/img/world-logos/germany/. Towns are from
// GERMAN_TOWNS.
//
// A club's region is the name fans use, which ZenGM's tables show on its own,
// and its name is its club type, which in German comes first in real life
// ("FC" "Bayern Munich", "SV" "Werder Bremen").

type Colors = RealClub["colors"];

const crest = (file: string) => `/img/world-logos/germany/${file}`;

const club = (
	region: string,
	name: string,
	abbrev: string,
	town: string,
	colors: Colors,
	imgURL: (colors: Colors) => string,
): RealClub => ({ region, name, abbrev, town, colors, imgURL: imgURL(colors) });

const file = (name: string) => () => crest(name);

export const GERMAN_CLUBS_BY_TIER: RealClub[][] = [
	[
		club(
			"Bayern Munich",
			"FC",
			"FCB",
			"Munich",
			["#dc052d", "#0066b2", "#ffffff"],
			file("bayern-munich.svg"),
		),
		club(
			"Bayer Leverkusen",
			"TSV",
			"B04",
			"Leverkusen",
			["#e32221", "#000000", "#ffffff"],
			file("bayer-leverkusen.svg"),
		),
		club(
			"Borussia Dortmund",
			"BVB",
			"BVB",
			"Dortmund",
			["#fde100", "#000000", "#ffffff"],
			file("borussia-dortmund.svg"),
		),
		club(
			"RB Leipzig",
			"FC",
			"RBL",
			"Leipzig",
			["#dd0741", "#001f47", "#ffffff"],
			file("rb-leipzig.svg"),
		),
		club(
			"Eintracht Frankfurt",
			"SGE",
			"SGE",
			"Frankfurt",
			["#e1000f", "#000000", "#ffffff"],
			file("eintracht-frankfurt.svg"),
		),
		club(
			"Stuttgart",
			"VfB",
			"VFB",
			"Stuttgart",
			["#e32219", "#ffffff", "#000000"],
			file("vfb-stuttgart.svg"),
		),
		club(
			"Borussia Mönchengladbach",
			"VfL",
			"BMG",
			"Mönchengladbach",
			["#000000", "#ffffff", "#00a94f"],
			file("borussia-monchengladbach.svg"),
		),
		club(
			"Wolfsburg",
			"VfL",
			"WOB",
			"Wolfsburg",
			["#65b32e", "#ffffff", "#000000"],
			file("vfl-wolfsburg.svg"),
		),
		club(
			"Freiburg",
			"SC",
			"SCF",
			"Freiburg",
			["#e2001a", "#000000", "#ffffff"],
			file("sc-freiburg.svg"),
		),
		club(
			"Werder Bremen",
			"SV",
			"SVW",
			"Bremen",
			["#1d9053", "#ffffff", "#000000"],
			file("werder-bremen.svg"),
		),
		club(
			"Mainz 05",
			"FSV",
			"M05",
			"Mainz",
			["#c3141e", "#ffffff", "#e3000f"],
			file("mainz-05.svg"),
		),
		club(
			"Hoffenheim",
			"TSG",
			"TSG",
			"Sinsheim",
			["#1961b5", "#ffffff", "#000000"],
			file("hoffenheim.svg"),
		),
		club(
			"Augsburg",
			"FC",
			"FCA",
			"Augsburg",
			["#ba3733", "#46714d", "#ffffff"],
			file("fc-augsburg.svg"),
		),
		club(
			"Union Berlin",
			"FC",
			"FCU",
			"Berlin",
			["#eb1923", "#ffed00", "#ffffff"],
			file("union-berlin.svg"),
		),
		club(
			"Bochum",
			"VfL",
			"BOC",
			"Bochum",
			["#005ca9", "#ffffff", "#000000"],
			file("vfl-bochum.svg"),
		),
		club(
			"Heidenheim",
			"FC",
			"FCH",
			"Heidenheim",
			["#e32219", "#003da5", "#ffffff"],
			file("heidenheim.svg"),
		),
		club(
			"St. Pauli",
			"FC",
			"STP",
			"Hamburg",
			["#684b3c", "#ffffff", "#df1e26"],
			file("st-pauli.svg"),
		),
		club(
			"Holstein Kiel",
			"KSV",
			"KSV",
			"Kiel",
			["#0055a4", "#ffffff", "#e30613"],
			file("holstein-kiel.svg"),
		),
		club(
			"Köln",
			"FC",
			"KOE",
			"Cologne",
			["#ed1c24", "#ffffff", "#000000"],
			file("koln.svg"),
		),
		club(
			"Hamburger SV",
			"HSV",
			"HSV",
			"Hamburg",
			["#0e53a7", "#ffffff", "#000000"],
			file("hamburger-sv.svg"),
		),
	],
	[
		club(
			"Hertha",
			"BSC",
			"BSC",
			"Berlin",
			["#004d9d", "#ffffff", "#000000"],
			file("hertha-bsc.svg"),
		),
		club(
			"Schalke 04",
			"FC",
			"S04",
			"Gelsenkirchen",
			["#004d9d", "#ffffff", "#000000"],
			file("schalke-04.svg"),
		),
		club(
			"Fortuna Düsseldorf",
			"FC",
			"F95",
			"Düsseldorf",
			["#e2001a", "#ffffff", "#000000"],
			file("fortuna-dusseldorf.svg"),
		),
		club(
			"Nürnberg",
			"FC",
			"FCN",
			"Nuremberg",
			["#ad1732", "#ffffff", "#000000"],
			file("nurnberg.svg"),
		),
		club(
			"Hannover 96",
			"SV",
			"H96",
			"Hanover",
			["#e30613", "#000000", "#ffffff"],
			file("hannover-96.svg"),
		),
		club(
			"Kaiserslautern",
			"FC",
			"FCK",
			"Kaiserslautern",
			["#e30613", "#ffffff", "#000000"],
			file("kaiserslautern.svg"),
		),
		club(
			"Karlsruher",
			"SC",
			"KSC",
			"Karlsruhe",
			["#0e4c92", "#ffffff", "#e30613"],
			file("karlsruher-sc.svg"),
		),
		club(
			"Darmstadt 98",
			"SV",
			"D98",
			"Darmstadt",
			["#004e9e", "#ffffff", "#000000"],
			file("darmstadt-98.svg"),
		),
		club(
			"Paderborn 07",
			"SC",
			"SCP",
			"Paderborn",
			["#004e9e", "#ffffff", "#000000"],
			file("paderborn-07.svg"),
		),
		club(
			"Eintracht Braunschweig",
			"BTSV",
			"EBS",
			"Braunschweig",
			["#f8b400", "#004b93", "#ffffff"],
			file("eintracht-braunschweig.svg"),
		),
		club(
			"Magdeburg",
			"FC",
			"FCM",
			"Magdeburg",
			["#006e3c", "#ffffff", "#000000"],
			file("magdeburg.svg"),
		),
		club(
			"Hansa Rostock",
			"FC",
			"HRO",
			"Rostock",
			["#004e9e", "#ffffff", "#000000"],
			file("hansa-rostock.svg"),
		),
		club(
			"Dynamo Dresden",
			"SG",
			"SGD",
			"Dresden",
			["#ffe500", "#000000", "#ffffff"],
			file("dynamo-dresden.svg"),
		),
		club(
			"Greuther Fürth",
			"SpVgg",
			"SGF",
			"Fürth",
			["#00915b", "#ffffff", "#000000"],
			file("greuther-furth.svg"),
		),
		club(
			"Elversberg",
			"SV",
			"SVE",
			"Saarbrücken",
			["#000000", "#e30613", "#ffffff"],
			file("elversberg.svg"),
		),
		club(
			"Arminia Bielefeld",
			"DSC",
			"ARM",
			"Bielefeld",
			["#00529b", "#ffffff", "#000000"],
			file("arminia-bielefeld.svg"),
		),
		club(
			"Duisburg",
			"MSV",
			"MSV",
			"Duisburg",
			["#004e9e", "#ffffff", "#000000"],
			file("msv-duisburg.svg"),
		),
		club(
			"Alemannia Aachen",
			"TSV",
			"ALE",
			"Aachen",
			["#ffe500", "#000000", "#ffffff"],
			file("alemannia-aachen.svg"),
		),
		club(
			"Rot-Weiss Essen",
			"FC",
			"RWE",
			"Essen",
			["#e2001a", "#ffffff", "#000000"],
			file("rot-weiss-essen.png"),
		),
		club(
			"Energie Cottbus",
			"FC",
			"ENC",
			"Cottbus",
			["#e2001a", "#ffffff", "#000000"],
			file("energie-cottbus.svg"),
		),
	],
];
