import type { RealClub } from "./worldCountries.ts";

// International Soccer Zen GM mod (Epic 7): Italy's real clubs, decided with
// the user. Each tier's clubs start roughly at their real standing (the 2025-26
// Serie A on top, Serie B below), in rough order of stature, so a smaller
// Division keeps the clubs at the top of its list. Towns are from ITALIAN_TOWNS.
//
// Crests are copied from Wikipedia into public/img/world-logos/italy/, each one
// the crest in its club's infobox. Juventus's is a plain black J, invisible on
// a dark page, so it was given the club's own white fill and black outline,
// which reads on both (the same treatment the American logos got).
//
// A club's region is the name fans use, which ZenGM's tables show on its own,
// and its name is the rest of its official name ("Hellas Verona" "FC"), or its
// club type when that comes first in real life ("Napoli" "SSC").
//
// Sassuolo plays in Reggio Emilia, its own town being far too small for one of
// its own.

const crest = (file: string) => `/img/world-logos/italy/${file}`;

const club = (
	region: string,
	name: string,
	abbrev: string,
	town: string,
	colors: RealClub["colors"],
	file: string,
): RealClub => ({ region, name, abbrev, town, colors, imgURL: crest(file) });

export const ITALIAN_CLUBS_BY_TIER: RealClub[][] = [
	[
		club(
			"Napoli",
			"SSC",
			"NAP",
			"Naples",
			["#12a0d7", "#ffffff", "#003d7c"],
			"napoli.svg",
		),
		club(
			"Inter",
			"Milano",
			"INT",
			"Milan",
			["#0068a8", "#000000", "#ffffff"],
			"inter-milan.svg",
		),
		club(
			"Milan",
			"AC",
			"ACM",
			"Milan",
			["#fb090b", "#000000", "#ffffff"],
			"ac-milan.svg",
		),
		club(
			"Juventus",
			"FC",
			"JUV",
			"Turin",
			["#000000", "#ffffff", "#d4af37"],
			"juventus.svg",
		),
		club(
			"Atalanta",
			"BC",
			"ATA",
			"Bergamo",
			["#1d1d1b", "#005ca9", "#ffffff"],
			"atalanta.svg",
		),
		club(
			"Roma",
			"AS",
			"ROM",
			"Rome",
			["#8e1f2f", "#f0bc42", "#ffffff"],
			"roma.svg",
		),
		club(
			"Lazio",
			"SS",
			"LAZ",
			"Rome",
			["#87d8f7", "#ffffff", "#0d2b52"],
			"lazio.svg",
		),
		club(
			"Fiorentina",
			"ACF",
			"FIO",
			"Florence",
			["#482e92", "#ffffff", "#c8102e"],
			"fiorentina.svg",
		),
		club(
			"Bologna",
			"FC",
			"BOL",
			"Bologna",
			["#a81736", "#1a2f48", "#ffffff"],
			"bologna.svg",
		),
		club(
			"Torino",
			"FC",
			"TRO",
			"Turin",
			["#881600", "#ffffff", "#c8a95c"],
			"torino.svg",
		),
		club(
			"Como",
			"1907",
			"COM",
			"Como",
			["#003d86", "#ffffff", "#c8102e"],
			"como.svg",
		),
		club(
			"Udinese",
			"Calcio",
			"UDI",
			"Udine",
			["#000000", "#ffffff", "#c8102e"],
			"udinese.svg",
		),
		club(
			"Genoa",
			"CFC",
			"GEN",
			"Genoa",
			["#b3132c", "#00265d", "#ffffff"],
			"genoa.svg",
		),
		club(
			"Hellas Verona",
			"FC",
			"VER",
			"Verona",
			["#002f6c", "#ffd400", "#ffffff"],
			"hellas-verona.svg",
		),
		club(
			"Cagliari",
			"Calcio",
			"CAG",
			"Cagliari",
			["#af1e2d", "#002454", "#ffffff"],
			"cagliari.svg",
		),
		club(
			"Parma",
			"Calcio",
			"PAR",
			"Parma",
			["#ffd200", "#004b87", "#ffffff"],
			"parma.svg",
		),
		club(
			"Lecce",
			"US",
			"LEC",
			"Lecce",
			["#ffe500", "#d2001e", "#ffffff"],
			"lecce.svg",
		),
		club(
			"Pisa",
			"SC",
			"PIS",
			"Pisa",
			["#00529f", "#000000", "#ffffff"],
			"pisa.svg",
		),
		club(
			"Sassuolo",
			"US",
			"SSU",
			"Reggio Emilia",
			["#00a752", "#000000", "#ffffff"],
			"sassuolo.svg",
		),
		club(
			"Cremonese",
			"US",
			"CRE",
			"Cremona",
			["#cd1719", "#ffffff", "#808285"],
			"cremonese.svg",
		),
	],
	[
		club(
			"Sampdoria",
			"UC",
			"SAM",
			"Genoa",
			["#1b5497", "#ffffff", "#c8102e"],
			"sampdoria.svg",
		),
		club(
			"Palermo",
			"FC",
			"PAL",
			"Palermo",
			["#f5a7c3", "#000000", "#ffffff"],
			"palermo.svg",
		),
		club(
			"Venezia",
			"FC",
			"VEZ",
			"Venice",
			["#000000", "#007a3d", "#f5821f"],
			"venezia.svg",
		),
		club(
			"Monza",
			"AC",
			"MNZ",
			"Monza",
			["#d5122a", "#ffffff", "#000000"],
			"monza.svg",
		),
		club(
			"Empoli",
			"FC",
			"EMP",
			"Empoli",
			["#00579c", "#ffffff", "#000000"],
			"empoli.svg",
		),
		club(
			"Spezia",
			"Calcio",
			"SPE",
			"La Spezia",
			["#ffffff", "#000000", "#c8102e"],
			"spezia.svg",
		),
		club(
			"Bari",
			"SSC",
			"BRI",
			"Bari",
			["#d8112a", "#ffffff", "#000000"],
			"bari.svg",
		),
		club(
			"Frosinone",
			"Calcio",
			"FRO",
			"Frosinone",
			["#fdd835", "#0e4c92", "#ffffff"],
			"frosinone.svg",
		),
		club(
			"Catanzaro",
			"US",
			"CAT",
			"Catanzaro",
			["#ffd500", "#e2001a", "#ffffff"],
			"catanzaro.svg",
		),
		club(
			"Cesena",
			"AC",
			"CES",
			"Cesena",
			["#ffffff", "#000000", "#c8102e"],
			"cesena.svg",
		),
		club(
			"Modena",
			"FC",
			"MOD",
			"Modena",
			["#ffdd00", "#0033a0", "#ffffff"],
			"modena.svg",
		),
		club(
			"Reggiana",
			"AC",
			"REG",
			"Reggio Emilia",
			["#d20a11", "#ffffff", "#000000"],
			"reggiana.svg",
		),
		club(
			"Pescara",
			"Delfino",
			"PES",
			"Pescara",
			["#1d3c9c", "#ffffff", "#87ceeb"],
			"pescara.svg",
		),
		club(
			"Padova",
			"Calcio",
			"PAD",
			"Padua",
			["#ffffff", "#c8102e", "#000000"],
			"padova.svg",
		),
		club(
			"Avellino",
			"US",
			"AVE",
			"Avellino",
			["#007a3d", "#ffffff", "#000000"],
			"avellino.svg",
		),
		club(
			"Südtirol",
			"FC",
			"SUD",
			"Bolzano",
			["#ffffff", "#c8102e", "#000000"],
			"sudtirol.svg",
		),
		club(
			"Juve Stabia",
			"SS",
			"JST",
			"Castellammare di Stabia",
			["#ffd500", "#0047ab", "#ffffff"],
			"juve-stabia.svg",
		),
		club(
			"Mantova",
			"1911",
			"MAN",
			"Mantua",
			["#c8102e", "#ffffff", "#0047ab"],
			"mantova.svg",
		),
		club(
			"Carrarese",
			"Calcio",
			"CRR",
			"Carrara",
			["#ffd500", "#0047ab", "#ffffff"],
			"carrarese.svg",
		),
		club(
			"Virtus Entella",
			"SS",
			"ENT",
			"Chiavari",
			["#0047ab", "#ffffff", "#000000"],
			"virtus-entella.svg",
		),
	],
];
