// International Soccer Zen GM mod (Epic 7): real towns for the pilot World's
// invented clubs. Decided: clubs are based in real towns, with invented names
// that don't copy real clubs (see isRealClubName). A town's `pop` is its rough
// population in thousands, only used to put bigger towns in higher tiers, and
// `wikipedia` is the title of its English Wikipedia article.

export type PilotTown = {
	name: string;
	// The shorter name a club takes, when it isn't the town's full name
	clubName?: string;
	pop: number;
	wikipedia: string;
};

export const ENGLISH_TOWNS: PilotTown[] = [
	{ name: "London", pop: 8900, wikipedia: "London" },
	{ name: "Birmingham", pop: 1140, wikipedia: "Birmingham" },
	{ name: "Leeds", pop: 800, wikipedia: "Leeds" },
	{ name: "Sheffield", pop: 580, wikipedia: "Sheffield" },
	{ name: "Manchester", pop: 550, wikipedia: "Manchester" },
	{ name: "Liverpool", pop: 490, wikipedia: "Liverpool" },
	{ name: "Bristol", pop: 470, wikipedia: "Bristol" },
	{ name: "Leicester", pop: 370, wikipedia: "Leicester" },
	{ name: "Bradford", pop: 350, wikipedia: "Bradford" },
	{ name: "Coventry", pop: 345, wikipedia: "Coventry" },
	{ name: "Nottingham", pop: 320, wikipedia: "Nottingham" },
	{
		name: "Newcastle upon Tyne",
		clubName: "Newcastle",
		pop: 300,
		wikipedia: "Newcastle_upon_Tyne",
	},
	{
		name: "Kingston upon Hull",
		clubName: "Hull",
		pop: 265,
		wikipedia: "Kingston_upon_Hull",
	},
	{ name: "Plymouth", pop: 265, wikipedia: "Plymouth" },
	{ name: "Wolverhampton", pop: 265, wikipedia: "Wolverhampton" },
	{ name: "Derby", pop: 260, wikipedia: "Derby" },
	{
		name: "Stoke-on-Trent",
		clubName: "Stoke",
		pop: 255,
		wikipedia: "Stoke-on-Trent",
	},
	{ name: "Southampton", pop: 250, wikipedia: "Southampton" },
	{ name: "Brighton", pop: 230, wikipedia: "Brighton" },
	{ name: "Milton Keynes", pop: 230, wikipedia: "Milton_Keynes" },
	{ name: "Luton", pop: 225, wikipedia: "Luton" },
	{ name: "Northampton", pop: 225, wikipedia: "Northampton" },
	{ name: "Portsmouth", pop: 210, wikipedia: "Portsmouth" },
	{ name: "Peterborough", pop: 200, wikipedia: "Peterborough" },
	{ name: "Swindon", pop: 185, wikipedia: "Swindon" },
	{
		name: "Southend-on-Sea",
		clubName: "Southend",
		pop: 180,
		wikipedia: "Southend-on-Sea",
	},
	{ name: "Middlesbrough", pop: 175, wikipedia: "Middlesbrough" },
	{ name: "Reading", pop: 175, wikipedia: "Reading,_Berkshire" },
	{ name: "Sunderland", pop: 175, wikipedia: "Sunderland" },
	{ name: "Oxford", pop: 160, wikipedia: "Oxford" },
	{ name: "York", pop: 150, wikipedia: "York" },
	{ name: "Cambridge", pop: 145, wikipedia: "Cambridge" },
	{ name: "Norwich", pop: 145, wikipedia: "Norwich" },
	{ name: "Preston", pop: 145, wikipedia: "Preston,_Lancashire" },
	{ name: "Blackpool", pop: 140, wikipedia: "Blackpool" },
	{ name: "Bolton", pop: 140, wikipedia: "Bolton" },
	{ name: "Huddersfield", pop: 140, wikipedia: "Huddersfield" },
	{ name: "Ipswich", pop: 140, wikipedia: "Ipswich" },
	{ name: "Colchester", pop: 130, wikipedia: "Colchester" },
	{ name: "Exeter", pop: 130, wikipedia: "Exeter" },
	{ name: "Gloucester", pop: 130, wikipedia: "Gloucester" },
	{ name: "Blackburn", pop: 120, wikipedia: "Blackburn" },
	{ name: "Cheltenham", pop: 115, wikipedia: "Cheltenham" },
	{ name: "Doncaster", pop: 110, wikipedia: "Doncaster" },
	{ name: "Rotherham", pop: 110, wikipedia: "Rotherham" },
	{ name: "Stockport", pop: 105, wikipedia: "Stockport" },
	{ name: "Wigan", pop: 105, wikipedia: "Wigan" },
	{ name: "Lincoln", pop: 100, wikipedia: "Lincoln,_England" },
	{ name: "Worcester", pop: 100, wikipedia: "Worcester,_England" },
	{ name: "Bath", pop: 95, wikipedia: "Bath,_Somerset" },
	{ name: "Chester", pop: 90, wikipedia: "Chester" },
	{ name: "Grimsby", pop: 85, wikipedia: "Grimsby" },
	{ name: "Scunthorpe", pop: 80, wikipedia: "Scunthorpe" },
	{ name: "Burnley", pop: 75, wikipedia: "Burnley" },
	{ name: "Carlisle", pop: 75, wikipedia: "Carlisle,_Cumbria" },
	{ name: "Harrogate", pop: 75, wikipedia: "Harrogate" },
	{ name: "Shrewsbury", pop: 75, wikipedia: "Shrewsbury" },
	{ name: "Canterbury", pop: 55, wikipedia: "Canterbury" },
	{ name: "Durham", pop: 50, wikipedia: "Durham,_England" },
	{ name: "Lancaster", pop: 50, wikipedia: "Lancaster,_Lancashire" },
	{ name: "Salisbury", pop: 40, wikipedia: "Salisbury" },
];

export const SPANISH_TOWNS: PilotTown[] = [
	{ name: "Madrid", pop: 3300, wikipedia: "Madrid" },
	{ name: "Barcelona", pop: 1620, wikipedia: "Barcelona" },
	{ name: "Valencia", pop: 790, wikipedia: "Valencia" },
	{ name: "Sevilla", pop: 685, wikipedia: "Seville" },
	{ name: "Zaragoza", pop: 675, wikipedia: "Zaragoza" },
	{ name: "Málaga", pop: 575, wikipedia: "Málaga" },
	{ name: "Murcia", pop: 460, wikipedia: "Murcia" },
	{ name: "Palma", pop: 415, wikipedia: "Palma_de_Mallorca" },
	{ name: "Las Palmas", pop: 380, wikipedia: "Las_Palmas" },
	{ name: "Bilbao", pop: 345, wikipedia: "Bilbao" },
	{ name: "Alicante", pop: 335, wikipedia: "Alicante" },
	{ name: "Córdoba", pop: 320, wikipedia: "Córdoba,_Spain" },
	{ name: "Valladolid", pop: 300, wikipedia: "Valladolid" },
	{ name: "Vigo", pop: 295, wikipedia: "Vigo" },
	{ name: "Gijón", pop: 270, wikipedia: "Gijón" },
	{
		name: "Vitoria-Gasteiz",
		clubName: "Vitoria",
		pop: 255,
		wikipedia: "Vitoria-Gasteiz",
	},
	{ name: "A Coruña", pop: 245, wikipedia: "A_Coruña" },
	{ name: "Elche", pop: 235, wikipedia: "Elche" },
	{ name: "Granada", pop: 230, wikipedia: "Granada" },
	{ name: "Badalona", pop: 225, wikipedia: "Badalona" },
	{ name: "Oviedo", pop: 220, wikipedia: "Oviedo" },
	{ name: "Cartagena", pop: 215, wikipedia: "Cartagena,_Spain" },
	{ name: "Sabadell", pop: 215, wikipedia: "Sabadell" },
	{
		name: "Jerez de la Frontera",
		clubName: "Jerez",
		pop: 212,
		wikipedia: "Jerez_de_la_Frontera",
	},
	{ name: "Móstoles", pop: 210, wikipedia: "Móstoles" },
	{
		name: "Santa Cruz de Tenerife",
		clubName: "Tenerife",
		pop: 210,
		wikipedia: "Santa_Cruz_de_Tenerife",
	},
	{ name: "Almería", pop: 200, wikipedia: "Almería" },
	{ name: "Pamplona", pop: 200, wikipedia: "Pamplona" },
	{
		name: "Alcalá de Henares",
		clubName: "Alcalá",
		pop: 195,
		wikipedia: "Alcalá_de_Henares",
	},
	{ name: "Fuenlabrada", pop: 190, wikipedia: "Fuenlabrada" },
	{ name: "Leganés", pop: 190, wikipedia: "Leganés" },
	{ name: "San Sebastián", pop: 187, wikipedia: "San_Sebastián" },
	{ name: "Getafe", pop: 185, wikipedia: "Getafe" },
	{ name: "Albacete", pop: 175, wikipedia: "Albacete" },
	{ name: "Burgos", pop: 175, wikipedia: "Burgos" },
	{
		name: "Castellón de la Plana",
		clubName: "Castellón",
		pop: 175,
		wikipedia: "Castellón_de_la_Plana",
	},
	{ name: "Santander", pop: 172, wikipedia: "Santander,_Spain" },
	{ name: "Badajoz", pop: 150, wikipedia: "Badajoz" },
	{ name: "Logroño", pop: 150, wikipedia: "Logroño" },
	{ name: "Marbella", pop: 147, wikipedia: "Marbella" },
	{ name: "Salamanca", pop: 145, wikipedia: "Salamanca" },
	{ name: "Huelva", pop: 142, wikipedia: "Huelva" },
	{ name: "Lleida", pop: 140, wikipedia: "Lleida" },
	{ name: "Tarragona", pop: 135, wikipedia: "Tarragona" },
	{ name: "Algeciras", pop: 123, wikipedia: "Algeciras" },
	{ name: "León", pop: 122, wikipedia: "León,_Spain" },
	{ name: "Cádiz", pop: 115, wikipedia: "Cádiz" },
	{ name: "Jaén", pop: 112, wikipedia: "Jaén,_Spain" },
	{ name: "Ourense", pop: 105, wikipedia: "Ourense" },
	{ name: "Girona", pop: 103, wikipedia: "Girona" },
	{ name: "Lugo", pop: 98, wikipedia: "Lugo" },
	{
		name: "Santiago de Compostela",
		clubName: "Santiago",
		pop: 98,
		wikipedia: "Santiago_de_Compostela",
	},
	{ name: "Cáceres", pop: 96, wikipedia: "Cáceres,_Spain" },
	{ name: "Toledo", pop: 85, wikipedia: "Toledo,_Spain" },
	{
		name: "Talavera de la Reina",
		clubName: "Talavera",
		pop: 83,
		wikipedia: "Talavera_de_la_Reina",
	},
	{ name: "Ferrol", pop: 64, wikipedia: "Ferrol,_Spain" },
	{ name: "Ponferrada", pop: 64, wikipedia: "Ponferrada" },
	{ name: "Mérida", pop: 60, wikipedia: "Mérida,_Spain" },
	{ name: "Zamora", pop: 60, wikipedia: "Zamora,_Spain" },
	{ name: "Huesca", pop: 53, wikipedia: "Huesca" },
];

// Real clubs in or near the pilot towns, from the professional leagues and
// some well-known others, which generated names must not copy. Best effort:
// countless amateur clubs share town names.
export const REAL_ENGLISH_CLUB_NAMES = [
	"Birmingham City",
	"Blackburn Rovers",
	"Blackpool",
	"Bolton Wanderers",
	"Bradford City",
	"Bradford Park Avenue",
	"Brighton Albion",
	"Brighton and Hove Albion",
	"Bristol City",
	"Bristol Rovers",
	"Burnley",
	"Cambridge City",
	"Cambridge United",
	"Canterbury City",
	"Carlisle United",
	"Cheltenham Town",
	"Chester",
	"Chester City",
	"Colchester United",
	"Coventry City",
	"Derby County",
	"Doncaster Rovers",
	"Durham City",
	"Exeter City",
	"Gloucester City",
	"Grimsby Town",
	"Harrogate Town",
	"Huddersfield Town",
	"Hull City",
	"Ipswich Town",
	"Lancaster City",
	"Leeds United",
	"Leicester City",
	"Lincoln City",
	"Liverpool",
	"London City",
	"Luton Town",
	"Manchester City",
	"Manchester United",
	"Mansfield Town",
	"Middlesbrough",
	"Milton Keynes Dons",
	"Newcastle United",
	"Northampton Town",
	"Norwich City",
	"Nottingham Forest",
	"Oxford City",
	"Oxford United",
	"Peterborough United",
	"Plymouth Argyle",
	"Portsmouth",
	"Preston North End",
	"Reading",
	"Rotherham United",
	"Salisbury City",
	"Scunthorpe United",
	"Sheffield United",
	"Sheffield Wednesday",
	"Shrewsbury Town",
	"Southampton",
	"Southend United",
	"Stockport County",
	"Stockport Town",
	"Stoke City",
	"Sunderland",
	"Swindon Town",
	"Wigan Athletic",
	"Wolverhampton Wanderers",
	"Worcester City",
	"York City",
];

export const REAL_SPANISH_CLUB_NAMES = [
	"AD Mérida",
	"Albacete Balompié",
	"Algeciras CF",
	"Athletic Club",
	"Atlético Baleares",
	"Atlético de Madrid",
	"Burgos CF",
	"CA Osasuna",
	"Cádiz CF",
	"CD Badajoz",
	"CD Castellón",
	"CD Leganés",
	"CD Lugo",
	"CD Móstoles",
	"CD Ourense",
	"CD Tenerife",
	"CD Toledo",
	"CE Sabadell",
	"Celta de Vigo",
	"CF Badalona",
	"CF Fuenlabrada",
	"CF Talavera de la Reina",
	"Córdoba CF",
	"CP Cacereño",
	"Cultural Leonesa",
	"Deportivo Alavés",
	"Deportivo de La Coruña",
	"Elche CF",
	"FC Barcelona",
	"FC Cartagena",
	"Getafe CF",
	"Gimnàstic de Tarragona",
	"Girona FC",
	"Granada CF",
	"Hércules CF",
	"Levante UD",
	"Málaga CF",
	"Marbella FC",
	"Mérida CF",
	"Racing de Ferrol",
	"Racing de Santander",
	"Rayo Vallecano",
	"RCD Espanyol de Barcelona",
	"RCD Mallorca",
	"Real Betis",
	"Real Jaén",
	"Real Madrid",
	"Real Murcia",
	"Real Oviedo",
	"Real Sociedad",
	"Real Sporting de Gijón",
	"Real Valladolid",
	"Real Zaragoza",
	"Recreativo de Huelva",
	"RSD Alcalá",
	"SD Compostela",
	"SD Eibar",
	"SD Huesca",
	"SD Logroñés",
	"SD Ponferradina",
	"Sevilla FC",
	"Sporting de Gijón",
	"Talavera CF",
	"UD Almería",
	"UD Las Palmas",
	"UD Logroñés",
	"UD Salamanca",
	"UE Lleida",
	"Valencia CF",
	"Xerez CD",
	"Zamora CF",
];

// Words that don't tell clubs apart: club types, articles, and "and"
const IGNORED_WORDS = new Set([
	"a",
	"ad",
	"afc",
	"and",
	"ca",
	"cd",
	"ce",
	"cf",
	"club",
	"cp",
	"de",
	"del",
	"el",
	"fc",
	"la",
	"rcd",
	"rsd",
	"sd",
	"ud",
	"ue",
]);

/**
 * A club name without accents, capitals, hyphens, or IGNORED_WORDS, so "Real
 * Sporting de Gijón" and "Sporting Gijón CF" compare the same
 */
export const normalizeClubName = (name: string) =>
	name
		.normalize("NFD")
		.replaceAll(/[̀-ͯ]/g, "")
		.toLowerCase()
		.replaceAll("&", " ")
		.split(/[\s-]+/)
		.filter((word) => word !== "" && !IGNORED_WORDS.has(word))
		.join(" ");

/** Whether `name` is the same as one of `realNames`, once both are normalized */
export const isRealClubName = (name: string, realNames: string[]) => {
	const normalized = normalizeClubName(name);
	return realNames.some(
		(realName) => normalizeClubName(realName) === normalized,
	);
};
