import type { RealClub } from "./worldCountries.ts";

// International Soccer Zen GM mod (Epic 7): Spain's real clubs, decided with
// the user. Each tier's clubs start roughly at their real standing (the 2025-26
// La Liga on top, Segunda below), in rough order of stature, so a smaller
// Division keeps the clubs at the top of its list. Crests are copied from
// Wikipedia into public/img/world-logos/spain/. Towns are from SPANISH_TOWNS.

const crest = (file: string) => `/img/world-logos/spain/${file}`;

const club = (
	region: string,
	name: string,
	abbrev: string,
	town: string,
	colors: RealClub["colors"],
	file: string,
): RealClub => ({ region, name, abbrev, town, colors, imgURL: crest(file) });

export const SPANISH_CLUBS_BY_TIER: RealClub[][] = [
	[
		club(
			"Real Madrid",
			"CF",
			"RMA",
			"Madrid",
			["#ffffff", "#febe10", "#00529f"],
			"real-madrid.svg",
		),
		club(
			"FC",
			"Barcelona",
			"BAR",
			"Barcelona",
			["#a50044", "#004d98", "#edbb00"],
			"barcelona.svg",
		),
		club(
			"Atlético",
			"Madrid",
			"ATM",
			"Madrid",
			["#cb3524", "#ffffff", "#272e61"],
			"atletico-madrid.svg",
		),
		club(
			"Athletic",
			"Club",
			"ATH",
			"Bilbao",
			["#ee2523", "#ffffff", "#000000"],
			"athletic-club.svg",
		),
		club(
			"Sevilla",
			"FC",
			"SEV",
			"Sevilla",
			["#ffffff", "#d71920", "#000000"],
			"sevilla.png",
		),
		club(
			"Real",
			"Betis",
			"BET",
			"Sevilla",
			["#00954c", "#ffffff", "#000000"],
			"real-betis.png",
		),
		club(
			"Real",
			"Sociedad",
			"RSO",
			"San Sebastián",
			["#0067b1", "#ffffff", "#e4b630"],
			"real-sociedad.svg",
		),
		club(
			"Villarreal",
			"CF",
			"VIL",
			"Villarreal",
			["#ffe667", "#005187", "#ffffff"],
			"villarreal.svg",
		),
		club(
			"Valencia",
			"CF",
			"VAL",
			"Valencia",
			["#ffffff", "#000000", "#ee3524"],
			"valencia.svg",
		),
		club(
			"Celta",
			"Vigo",
			"CLT",
			"Vigo",
			["#8ac3ee", "#ffffff", "#e5254e"],
			"celta-vigo.svg",
		),
		club(
			"CA",
			"Osasuna",
			"OSA",
			"Pamplona",
			["#d91a21", "#0a346f", "#ffffff"],
			"osasuna.svg",
		),
		club(
			"Girona",
			"FC",
			"GIR",
			"Girona",
			["#cd2534", "#ffffff", "#000000"],
			"girona.svg",
		),
		club(
			"Rayo",
			"Vallecano",
			"RAY",
			"Madrid",
			["#ffffff", "#e53027", "#000000"],
			"rayo-vallecano.svg",
		),
		club(
			"Getafe",
			"CF",
			"GET",
			"Getafe",
			["#005999", "#ffffff", "#e42929"],
			"getafe.png",
		),
		club(
			"RCD",
			"Espanyol",
			"ESP",
			"Barcelona",
			["#007fc8", "#ffffff", "#000000"],
			"espanyol.svg",
		),
		club(
			"RCD",
			"Mallorca",
			"MLL",
			"Palma",
			["#e20613", "#000000", "#ffe667"],
			"mallorca.svg",
		),
		club(
			"Deportivo",
			"Alavés",
			"ALA",
			"Vitoria-Gasteiz",
			["#0761af", "#ffffff", "#000000"],
			"alaves.svg",
		),
		club(
			"Levante",
			"UD",
			"LEV",
			"Valencia",
			["#b4053f", "#004d98", "#ffffff"],
			"levante.svg",
		),
		club(
			"Elche",
			"CF",
			"ELC",
			"Elche",
			["#ffffff", "#05642c", "#000000"],
			"elche.svg",
		),
		club(
			"Real",
			"Oviedo",
			"OVI",
			"Oviedo",
			["#0d3b8d", "#ffffff", "#000000"],
			"real-oviedo.svg",
		),
	],
	[
		club(
			"Deportivo",
			"La Coruña",
			"DEP",
			"A Coruña",
			["#004a99", "#ffffff", "#000000"],
			"deportivo-la-coruna.svg",
		),
		club(
			"Real",
			"Zaragoza",
			"ZAR",
			"Zaragoza",
			["#ffffff", "#0e4c92", "#000000"],
			"real-zaragoza.svg",
		),
		club(
			"Málaga",
			"CF",
			"MAL",
			"Málaga",
			["#0b64b4", "#ffffff", "#000000"],
			"malaga.svg",
		),
		club(
			"UD",
			"Las Palmas",
			"LPA",
			"Las Palmas",
			["#ffe400", "#0055a4", "#ffffff"],
			"las-palmas.png",
		),
		club(
			"Real",
			"Valladolid",
			"VLL",
			"Valladolid",
			["#5b2c83", "#ffffff", "#000000"],
			"real-valladolid.svg",
		),
		club(
			"Sporting",
			"Gijón",
			"SPG",
			"Gijón",
			["#d21f26", "#ffffff", "#000000"],
			"sporting-gijon.svg",
		),
		club(
			"Racing",
			"Santander",
			"RAC",
			"Santander",
			["#ffffff", "#00804b", "#000000"],
			"racing-santander.svg",
		),
		club(
			"Granada",
			"CF",
			"GRA",
			"Granada",
			["#e0001a", "#ffffff", "#000000"],
			"granada.svg",
		),
		club(
			"Cádiz",
			"CF",
			"CAD",
			"Cádiz",
			["#ffe600", "#0048a1", "#ffffff"],
			"cadiz.svg",
		),
		club(
			"UD",
			"Almería",
			"ALM",
			"Almería",
			["#ee1119", "#ffffff", "#000000"],
			"almeria.svg",
		),
		club(
			"CD",
			"Leganés",
			"LEG",
			"Leganés",
			["#0033a0", "#ffffff", "#000000"],
			"leganes.svg",
		),
		club(
			"SD",
			"Eibar",
			"EIB",
			"Eibar",
			["#a50044", "#004d98", "#ffffff"],
			"eibar.svg",
		),
		club(
			"SD",
			"Huesca",
			"HUE",
			"Huesca",
			["#1f3a93", "#c8102e", "#ffffff"],
			"huesca.svg",
		),
		club(
			"Córdoba",
			"CF",
			"COR",
			"Córdoba",
			["#007a3d", "#ffffff", "#000000"],
			"cordoba.svg",
		),
		club(
			"Albacete",
			"Balompié",
			"ALB",
			"Albacete",
			["#ffffff", "#000000", "#c8102e"],
			"albacete.svg",
		),
		club(
			"Burgos",
			"CF",
			"BRG",
			"Burgos",
			["#000000", "#ffffff", "#c8102e"],
			"burgos.svg",
		),
		club(
			"CD",
			"Castellón",
			"CAS",
			"Castellón de la Plana",
			["#000000", "#ffffff", "#c8102e"],
			"castellon.svg",
		),
		club(
			"Cultural",
			"Leonesa",
			"CUL",
			"León",
			["#ffffff", "#000000", "#c8102e"],
			"cultural-leonesa.svg",
		),
		club(
			"CD",
			"Mirandés",
			"MIR",
			"Miranda de Ebro",
			["#e30613", "#000000", "#ffffff"],
			"mirandes.svg",
		),
		club(
			"AD",
			"Ceuta",
			"CEU",
			"Ceuta",
			["#ffffff", "#000000", "#c8102e"],
			"ceuta.svg",
		),
	],
];
