import type { PilotTown } from "./pilotTowns.ts";

// International Soccer Zen GM mod (Epic 7): real towns and real club names for
// the World's other Countries (England and Spain are in pilotTowns.ts). The
// same rules apply: a town's `pop` is its rough population in thousands, and
// `wikipedia` is the title of its English Wikipedia article.

export const AMERICAN_TOWNS: PilotTown[] = [
	{
		name: "New York City",
		clubName: "New York",
		pop: 8300,
		wikipedia: "New_York_City",
	},
	{ name: "Los Angeles", pop: 3900, wikipedia: "Los_Angeles" },
	{ name: "Chicago", pop: 2700, wikipedia: "Chicago" },
	{ name: "Houston", pop: 2300, wikipedia: "Houston" },
	{ name: "Phoenix", pop: 1650, wikipedia: "Phoenix,_Arizona" },
	{ name: "Philadelphia", pop: 1550, wikipedia: "Philadelphia" },
	{ name: "San Antonio", pop: 1450, wikipedia: "San_Antonio" },
	{ name: "San Diego", pop: 1390, wikipedia: "San_Diego" },
	{ name: "Dallas", pop: 1300, wikipedia: "Dallas" },
	{ name: "Jacksonville", pop: 970, wikipedia: "Jacksonville,_Florida" },
	{ name: "Austin", pop: 960, wikipedia: "Austin,_Texas" },
	{ name: "Fort Worth", pop: 950, wikipedia: "Fort_Worth,_Texas" },
	{ name: "San Jose", pop: 970, wikipedia: "San_Jose,_California" },
	{ name: "Columbus", pop: 910, wikipedia: "Columbus,_Ohio" },
	{ name: "Charlotte", pop: 900, wikipedia: "Charlotte,_North_Carolina" },
	{ name: "Indianapolis", pop: 880, wikipedia: "Indianapolis" },
	{ name: "San Francisco", pop: 810, wikipedia: "San_Francisco" },
	{ name: "Seattle", pop: 750, wikipedia: "Seattle" },
	{ name: "Denver", pop: 715, wikipedia: "Denver" },
	{ name: "Washington", pop: 680, wikipedia: "Washington,_D.C." },
	{ name: "Nashville", pop: 690, wikipedia: "Nashville,_Tennessee" },
	{ name: "Oklahoma City", pop: 700, wikipedia: "Oklahoma_City" },
	{ name: "El Paso", pop: 680, wikipedia: "El_Paso,_Texas" },
	{ name: "Boston", pop: 650, wikipedia: "Boston" },
	{ name: "Portland", pop: 630, wikipedia: "Portland,_Oregon" },
	{ name: "Las Vegas", pop: 660, wikipedia: "Las_Vegas" },
	{ name: "Detroit", pop: 630, wikipedia: "Detroit" },
	{ name: "Memphis", pop: 620, wikipedia: "Memphis,_Tennessee" },
	{ name: "Louisville", pop: 620, wikipedia: "Louisville,_Kentucky" },
	{ name: "Baltimore", pop: 570, wikipedia: "Baltimore" },
	{ name: "Milwaukee", pop: 560, wikipedia: "Milwaukee" },
	{ name: "Albuquerque", pop: 560, wikipedia: "Albuquerque,_New_Mexico" },
	{ name: "Tucson", pop: 545, wikipedia: "Tucson,_Arizona" },
	{ name: "Fresno", pop: 545, wikipedia: "Fresno,_California" },
	{ name: "Sacramento", pop: 525, wikipedia: "Sacramento,_California" },
	{ name: "Kansas City", pop: 510, wikipedia: "Kansas_City,_Missouri" },
	{ name: "Atlanta", pop: 500, wikipedia: "Atlanta" },
	{ name: "Omaha", pop: 485, wikipedia: "Omaha,_Nebraska" },
	{ name: "Raleigh", pop: 470, wikipedia: "Raleigh,_North_Carolina" },
	{ name: "Miami", pop: 450, wikipedia: "Miami" },
	{ name: "Minneapolis", pop: 425, wikipedia: "Minneapolis" },
	{ name: "Tulsa", pop: 410, wikipedia: "Tulsa,_Oklahoma" },
	{ name: "Oakland", pop: 435, wikipedia: "Oakland,_California" },
	{ name: "Tampa", pop: 400, wikipedia: "Tampa,_Florida" },
	{ name: "New Orleans", pop: 365, wikipedia: "New_Orleans" },
	{ name: "Wichita", pop: 395, wikipedia: "Wichita,_Kansas" },
	{ name: "Cleveland", pop: 360, wikipedia: "Cleveland" },
	{ name: "Honolulu", pop: 345, wikipedia: "Honolulu" },
	{ name: "St. Louis", pop: 290, wikipedia: "St._Louis" },
	{ name: "Pittsburgh", pop: 300, wikipedia: "Pittsburgh" },
	{ name: "Cincinnati", pop: 310, wikipedia: "Cincinnati" },
	{ name: "Orlando", pop: 310, wikipedia: "Orlando,_Florida" },
	{ name: "Anchorage", pop: 290, wikipedia: "Anchorage,_Alaska" },
	{ name: "Buffalo", pop: 275, wikipedia: "Buffalo,_New_York" },
	{ name: "Madison", pop: 270, wikipedia: "Madison,_Wisconsin" },
	{ name: "Boise", pop: 235, wikipedia: "Boise,_Idaho" },
	{ name: "Richmond", pop: 230, wikipedia: "Richmond,_Virginia" },
	{ name: "Spokane", pop: 230, wikipedia: "Spokane,_Washington" },
	{ name: "Birmingham", pop: 195, wikipedia: "Birmingham,_Alabama" },
	{
		name: "Salt Lake City",
		clubName: "Salt Lake",
		pop: 210,
		wikipedia: "Salt_Lake_City",
	},
	{ name: "Des Moines", pop: 210, wikipedia: "Des_Moines,_Iowa" },
	{ name: "Rochester", pop: 210, wikipedia: "Rochester,_New_York" },
	{ name: "Providence", pop: 190, wikipedia: "Providence,_Rhode_Island" },
	{ name: "Knoxville", pop: 195, wikipedia: "Knoxville,_Tennessee" },
	{ name: "Chattanooga", pop: 185, wikipedia: "Chattanooga,_Tennessee" },
	{ name: "Savannah", pop: 150, wikipedia: "Savannah,_Georgia" },
	{ name: "Charleston", pop: 155, wikipedia: "Charleston,_South_Carolina" },
	{ name: "Hartford", pop: 120, wikipedia: "Hartford,_Connecticut" },
	{ name: "Burlington", pop: 45, wikipedia: "Burlington,_Vermont" },
	{ name: "Missoula", pop: 75, wikipedia: "Missoula,_Montana" },
	// International Soccer Zen GM mod (Epic 7): cities for real clubs (see
	// competition/americanClubs.ts)
	{
		name: "Colorado Springs",
		pop: 480,
		wikipedia: "Colorado_Springs,_Colorado",
	},
	{ name: "Baton Rouge", pop: 222, wikipedia: "Baton_Rouge,_Louisiana" },
	{ name: "Little Rock", pop: 203, wikipedia: "Little_Rock,_Arkansas" },
	{ name: "Syracuse", pop: 145, wikipedia: "Syracuse,_New_York" },
	{ name: "Green Bay", pop: 107, wikipedia: "Green_Bay,_Wisconsin" },
];

export const MEXICAN_TOWNS: PilotTown[] = [
	{
		name: "Mexico City",
		clubName: "México",
		pop: 9200,
		wikipedia: "Mexico_City",
	},
	{ name: "Guadalajara", pop: 1400, wikipedia: "Guadalajara" },
	{ name: "Monterrey", pop: 1150, wikipedia: "Monterrey" },
	{ name: "Puebla", pop: 1690, wikipedia: "Puebla_(city)" },
	{ name: "Tijuana", pop: 1920, wikipedia: "Tijuana" },
	{ name: "León", pop: 1720, wikipedia: "León,_Guanajuato" },
	{
		name: "Ciudad Juárez",
		clubName: "Juárez",
		pop: 1510,
		wikipedia: "Ciudad_Juárez",
	},
	{ name: "Zapopan", pop: 1480, wikipedia: "Zapopan" },
	{ name: "Mérida", pop: 990, wikipedia: "Mérida,_Yucatán" },
	{
		name: "San Luis Potosí",
		clubName: "San Luis",
		pop: 910,
		wikipedia: "San_Luis_Potosí_(city)",
	},
	{ name: "Aguascalientes", pop: 950, wikipedia: "Aguascalientes_(city)" },
	{ name: "Hermosillo", pop: 940, wikipedia: "Hermosillo" },
	{ name: "Saltillo", pop: 880, wikipedia: "Saltillo" },
	{ name: "Mexicali", pop: 1050, wikipedia: "Mexicali" },
	{ name: "Culiacán", pop: 1000, wikipedia: "Culiacán" },
	{ name: "Querétaro", pop: 1050, wikipedia: "Querétaro_City" },
	{ name: "Chihuahua", pop: 940, wikipedia: "Chihuahua_(city)" },
	{ name: "Morelia", pop: 850, wikipedia: "Morelia" },
	{ name: "Toluca", pop: 910, wikipedia: "Toluca" },
	{ name: "Cancún", pop: 890, wikipedia: "Cancún" },
	{ name: "Torreón", pop: 720, wikipedia: "Torreón" },
	{ name: "Acapulco", pop: 780, wikipedia: "Acapulco" },
	{ name: "Tlaxcala", pop: 100, wikipedia: "Tlaxcala_(city)" },
	{ name: "Veracruz", pop: 610, wikipedia: "Veracruz_(city)" },
	{ name: "Villahermosa", pop: 680, wikipedia: "Villahermosa" },
	{ name: "Cuernavaca", pop: 380, wikipedia: "Cuernavaca" },
	{
		name: "Tuxtla Gutiérrez",
		clubName: "Tuxtla",
		pop: 600,
		wikipedia: "Tuxtla_Gutiérrez",
	},
	{ name: "Durango", pop: 690, wikipedia: "Victoria_de_Durango" },
	{ name: "Mazatlán", pop: 500, wikipedia: "Mazatlán" },
	{ name: "Irapuato", pop: 590, wikipedia: "Irapuato" },
	{ name: "Celaya", pop: 520, wikipedia: "Celaya" },
	{ name: "Pachuca", pop: 310, wikipedia: "Pachuca" },
	{ name: "Oaxaca", pop: 270, wikipedia: "Oaxaca_City" },
	{ name: "Xalapa", pop: 490, wikipedia: "Xalapa" },
	{ name: "Tampico", pop: 300, wikipedia: "Tampico" },
	{
		name: "Ciudad Victoria",
		clubName: "Victoria",
		pop: 350,
		wikipedia: "Ciudad_Victoria",
	},
	{ name: "Zacatecas", pop: 150, wikipedia: "Zacatecas_City" },
	{ name: "Tepic", pop: 425, wikipedia: "Tepic" },
	{ name: "La Paz", pop: 290, wikipedia: "La_Paz,_Baja_California_Sur" },
	{ name: "Campeche", pop: 250, wikipedia: "Campeche_City" },
	{ name: "Colima", pop: 160, wikipedia: "Colima_City" },
	{ name: "Ensenada", pop: 440, wikipedia: "Ensenada,_Baja_California" },
	{ name: "Nuevo Laredo", pop: 420, wikipedia: "Nuevo_Laredo" },
	{ name: "Reynosa", pop: 700, wikipedia: "Reynosa" },
	{ name: "Matamoros", pop: 540, wikipedia: "Matamoros,_Tamaulipas" },
	{ name: "Tepatitlán", pop: 150, wikipedia: "Tepatitlán_de_Morelos" },
	{ name: "Guanajuato", pop: 195, wikipedia: "Guanajuato_City" },
	{ name: "Uruapan", pop: 360, wikipedia: "Uruapan" },
	{ name: "Chilpancingo", pop: 280, wikipedia: "Chilpancingo" },
	{
		name: "Puerto Vallarta",
		clubName: "Vallarta",
		pop: 290,
		wikipedia: "Puerto_Vallarta",
	},
];

export const ITALIAN_TOWNS: PilotTown[] = [
	{ name: "Rome", clubName: "Roma", pop: 2750, wikipedia: "Rome" },
	{ name: "Milan", clubName: "Milano", pop: 1370, wikipedia: "Milan" },
	{ name: "Naples", clubName: "Napoli", pop: 910, wikipedia: "Naples" },
	{ name: "Turin", clubName: "Torino", pop: 850, wikipedia: "Turin" },
	{ name: "Palermo", pop: 630, wikipedia: "Palermo" },
	{ name: "Genoa", clubName: "Genova", pop: 560, wikipedia: "Genoa" },
	{ name: "Bologna", pop: 390, wikipedia: "Bologna" },
	{ name: "Florence", clubName: "Firenze", pop: 360, wikipedia: "Florence" },
	{ name: "Bari", pop: 315, wikipedia: "Bari" },
	{ name: "Catania", pop: 300, wikipedia: "Catania" },
	{ name: "Verona", pop: 255, wikipedia: "Verona" },
	{ name: "Venice", clubName: "Venezia", pop: 250, wikipedia: "Venice" },
	{ name: "Messina", pop: 220, wikipedia: "Messina" },
	{ name: "Padua", clubName: "Padova", pop: 210, wikipedia: "Padua" },
	{ name: "Trieste", pop: 200, wikipedia: "Trieste" },
	{ name: "Brescia", pop: 196, wikipedia: "Brescia" },
	{ name: "Parma", pop: 196, wikipedia: "Parma" },
	{ name: "Taranto", pop: 190, wikipedia: "Taranto" },
	{ name: "Prato", pop: 195, wikipedia: "Prato" },
	{ name: "Modena", pop: 185, wikipedia: "Modena" },
	{ name: "Reggio Calabria", pop: 170, wikipedia: "Reggio_Calabria" },
	{ name: "Reggio Emilia", pop: 170, wikipedia: "Reggio_Emilia" },
	{ name: "Perugia", pop: 162, wikipedia: "Perugia" },
	{ name: "Livorno", pop: 155, wikipedia: "Livorno" },
	{ name: "Ravenna", pop: 155, wikipedia: "Ravenna" },
	{ name: "Cagliari", pop: 150, wikipedia: "Cagliari" },
	{ name: "Foggia", pop: 148, wikipedia: "Foggia" },
	{ name: "Rimini", pop: 150, wikipedia: "Rimini" },
	{ name: "Salerno", pop: 128, wikipedia: "Salerno" },
	{ name: "Ferrara", pop: 130, wikipedia: "Ferrara" },
	{ name: "Sassari", pop: 125, wikipedia: "Sassari" },
	{ name: "Latina", pop: 127, wikipedia: "Latina,_Lazio" },
	{ name: "Monza", pop: 123, wikipedia: "Monza" },
	{ name: "Pescara", pop: 118, wikipedia: "Pescara" },
	{ name: "Bergamo", pop: 120, wikipedia: "Bergamo" },
	{ name: "Trento", pop: 118, wikipedia: "Trento" },
	{ name: "Vicenza", pop: 110, wikipedia: "Vicenza" },
	{ name: "Terni", pop: 108, wikipedia: "Terni" },
	{ name: "Bolzano", pop: 107, wikipedia: "Bolzano" },
	{ name: "Novara", pop: 102, wikipedia: "Novara" },
	{ name: "Piacenza", pop: 103, wikipedia: "Piacenza" },
	{ name: "Ancona", pop: 100, wikipedia: "Ancona" },
	{ name: "Udine", pop: 99, wikipedia: "Udine" },
	{ name: "Arezzo", pop: 98, wikipedia: "Arezzo" },
	{ name: "Cesena", pop: 96, wikipedia: "Cesena" },
	{ name: "Lecce", pop: 95, wikipedia: "Lecce" },
	{ name: "La Spezia", clubName: "Spezia", pop: 93, wikipedia: "La_Spezia" },
	{ name: "Pisa", pop: 90, wikipedia: "Pisa" },
	{ name: "Como", pop: 85, wikipedia: "Como" },
	{ name: "Varese", pop: 80, wikipedia: "Varese" },
	{ name: "Siena", pop: 54, wikipedia: "Siena" },
	{ name: "Lucca", pop: 89, wikipedia: "Lucca" },
	{ name: "Catanzaro", pop: 85, wikipedia: "Catanzaro" },
	{ name: "Cosenza", pop: 65, wikipedia: "Cosenza" },
	{ name: "Avellino", pop: 53, wikipedia: "Avellino" },
];

export const GERMAN_TOWNS: PilotTown[] = [
	{ name: "Berlin", pop: 3700, wikipedia: "Berlin" },
	{ name: "Hamburg", pop: 1850, wikipedia: "Hamburg" },
	{ name: "Munich", clubName: "München", pop: 1500, wikipedia: "Munich" },
	{ name: "Cologne", clubName: "Köln", pop: 1080, wikipedia: "Cologne" },
	{ name: "Frankfurt", pop: 770, wikipedia: "Frankfurt" },
	{ name: "Stuttgart", pop: 630, wikipedia: "Stuttgart" },
	{ name: "Düsseldorf", pop: 630, wikipedia: "Düsseldorf" },
	{ name: "Leipzig", pop: 620, wikipedia: "Leipzig" },
	{ name: "Dortmund", pop: 590, wikipedia: "Dortmund" },
	{ name: "Essen", pop: 580, wikipedia: "Essen" },
	{ name: "Bremen", pop: 570, wikipedia: "Bremen" },
	{ name: "Dresden", pop: 560, wikipedia: "Dresden" },
	{ name: "Hanover", clubName: "Hannover", pop: 540, wikipedia: "Hanover" },
	{ name: "Nuremberg", clubName: "Nürnberg", pop: 525, wikipedia: "Nuremberg" },
	{ name: "Duisburg", pop: 500, wikipedia: "Duisburg" },
	{ name: "Bochum", pop: 365, wikipedia: "Bochum" },
	{ name: "Wuppertal", pop: 355, wikipedia: "Wuppertal" },
	{ name: "Bielefeld", pop: 335, wikipedia: "Bielefeld" },
	{ name: "Bonn", pop: 335, wikipedia: "Bonn" },
	{ name: "Münster", pop: 320, wikipedia: "Münster" },
	{ name: "Mannheim", pop: 315, wikipedia: "Mannheim" },
	{ name: "Karlsruhe", pop: 310, wikipedia: "Karlsruhe" },
	{ name: "Augsburg", pop: 300, wikipedia: "Augsburg" },
	{ name: "Wiesbaden", pop: 280, wikipedia: "Wiesbaden" },
	{
		name: "Mönchengladbach",
		clubName: "Gladbach",
		pop: 265,
		wikipedia: "Mönchengladbach",
	},
	{ name: "Gelsenkirchen", pop: 260, wikipedia: "Gelsenkirchen" },
	{ name: "Aachen", pop: 250, wikipedia: "Aachen" },
	{ name: "Braunschweig", pop: 250, wikipedia: "Braunschweig" },
	{ name: "Kiel", pop: 245, wikipedia: "Kiel" },
	{ name: "Chemnitz", pop: 245, wikipedia: "Chemnitz" },
	{ name: "Halle", pop: 240, wikipedia: "Halle_(Saale)" },
	{ name: "Magdeburg", pop: 240, wikipedia: "Magdeburg" },
	{ name: "Freiburg", pop: 230, wikipedia: "Freiburg_im_Breisgau" },
	{ name: "Krefeld", pop: 227, wikipedia: "Krefeld" },
	{ name: "Mainz", pop: 220, wikipedia: "Mainz" },
	{ name: "Lübeck", pop: 217, wikipedia: "Lübeck" },
	{ name: "Erfurt", pop: 214, wikipedia: "Erfurt" },
	{ name: "Oberhausen", pop: 210, wikipedia: "Oberhausen" },
	{ name: "Rostock", pop: 209, wikipedia: "Rostock" },
	{ name: "Kassel", pop: 202, wikipedia: "Kassel" },
	{ name: "Hagen", pop: 190, wikipedia: "Hagen" },
	{ name: "Saarbrücken", pop: 180, wikipedia: "Saarbrücken" },
	{ name: "Potsdam", pop: 185, wikipedia: "Potsdam" },
	{ name: "Leverkusen", pop: 165, wikipedia: "Leverkusen" },
	{ name: "Oldenburg", pop: 170, wikipedia: "Oldenburg" },
	{ name: "Osnabrück", pop: 165, wikipedia: "Osnabrück" },
	{ name: "Heidelberg", pop: 160, wikipedia: "Heidelberg" },
	{ name: "Darmstadt", pop: 160, wikipedia: "Darmstadt" },
	{ name: "Regensburg", pop: 155, wikipedia: "Regensburg" },
	{ name: "Würzburg", pop: 128, wikipedia: "Würzburg" },
	{ name: "Wolfsburg", pop: 125, wikipedia: "Wolfsburg" },
	{ name: "Ulm", pop: 127, wikipedia: "Ulm" },
	{ name: "Ingolstadt", pop: 138, wikipedia: "Ingolstadt" },
	{ name: "Jena", pop: 110, wikipedia: "Jena" },
	{ name: "Cottbus", pop: 98, wikipedia: "Cottbus" },
	{ name: "Paderborn", pop: 150, wikipedia: "Paderborn" },
];

export const JAPANESE_TOWNS: PilotTown[] = [
	{ name: "Tokyo", pop: 9700, wikipedia: "Tokyo" },
	{ name: "Yokohama", pop: 3770, wikipedia: "Yokohama" },
	{ name: "Osaka", pop: 2750, wikipedia: "Osaka" },
	{ name: "Nagoya", pop: 2330, wikipedia: "Nagoya" },
	{ name: "Sapporo", pop: 1960, wikipedia: "Sapporo" },
	{ name: "Fukuoka", pop: 1610, wikipedia: "Fukuoka" },
	{ name: "Kobe", pop: 1520, wikipedia: "Kobe" },
	{ name: "Kawasaki", pop: 1540, wikipedia: "Kawasaki,_Kanagawa" },
	{ name: "Kyoto", pop: 1460, wikipedia: "Kyoto" },
	{ name: "Saitama", pop: 1340, wikipedia: "Saitama_(city)" },
	{ name: "Hiroshima", pop: 1190, wikipedia: "Hiroshima" },
	{ name: "Sendai", pop: 1090, wikipedia: "Sendai" },
	{ name: "Chiba", pop: 980, wikipedia: "Chiba_(city)" },
	{ name: "Kitakyushu", pop: 930, wikipedia: "Kitakyushu" },
	{ name: "Sakai", pop: 820, wikipedia: "Sakai" },
	{ name: "Niigata", pop: 780, wikipedia: "Niigata_(city)" },
	{ name: "Hamamatsu", pop: 790, wikipedia: "Hamamatsu" },
	{ name: "Kumamoto", pop: 740, wikipedia: "Kumamoto" },
	{ name: "Sagamihara", pop: 720, wikipedia: "Sagamihara" },
	{ name: "Shizuoka", pop: 690, wikipedia: "Shizuoka_(city)" },
	{ name: "Okayama", pop: 720, wikipedia: "Okayama" },
	{ name: "Kagoshima", pop: 600, wikipedia: "Kagoshima" },
	{ name: "Hachioji", pop: 580, wikipedia: "Hachiōji" },
	{ name: "Utsunomiya", pop: 520, wikipedia: "Utsunomiya" },
	{ name: "Matsuyama", pop: 510, wikipedia: "Matsuyama" },
	{ name: "Kanazawa", pop: 460, wikipedia: "Kanazawa" },
	{ name: "Oita", pop: 480, wikipedia: "Ōita_(city)" },
	{ name: "Nagasaki", pop: 400, wikipedia: "Nagasaki" },
	{ name: "Toyama", pop: 410, wikipedia: "Toyama_(city)" },
	{ name: "Gifu", pop: 400, wikipedia: "Gifu" },
	{ name: "Miyazaki", pop: 400, wikipedia: "Miyazaki_(city)" },
	{ name: "Nagano", pop: 370, wikipedia: "Nagano_(city)" },
	{ name: "Takamatsu", pop: 420, wikipedia: "Takamatsu" },
	{ name: "Kochi", pop: 320, wikipedia: "Kōchi" },
	{ name: "Naha", pop: 320, wikipedia: "Naha" },
	{ name: "Akita", pop: 300, wikipedia: "Akita_(city)" },
	{ name: "Aomori", pop: 270, wikipedia: "Aomori" },
	{ name: "Morioka", pop: 280, wikipedia: "Morioka" },
	{ name: "Fukushima", pop: 280, wikipedia: "Fukushima_(city)" },
	{ name: "Mito", pop: 270, wikipedia: "Mito,_Ibaraki" },
	{ name: "Kofu", pop: 185, wikipedia: "Kōfu" },
	{ name: "Yamagata", pop: 245, wikipedia: "Yamagata,_Yamagata" },
	{ name: "Tottori", pop: 185, wikipedia: "Tottori_(city)" },
	{ name: "Tokushima", pop: 250, wikipedia: "Tokushima_(city)" },
	{ name: "Nara", pop: 355, wikipedia: "Nara_(city)" },
	{ name: "Wakayama", pop: 360, wikipedia: "Wakayama_(city)" },
	{ name: "Matsumoto", pop: 240, wikipedia: "Matsumoto,_Nagano" },
	{ name: "Numazu", pop: 190, wikipedia: "Numazu" },
	{ name: "Hakodate", pop: 250, wikipedia: "Hakodate" },
	{ name: "Asahikawa", pop: 330, wikipedia: "Asahikawa" },
	{ name: "Iwaki", pop: 330, wikipedia: "Iwaki,_Fukushima" },
	{ name: "Imabari", pop: 150, wikipedia: "Imabari" },
];

// Real clubs in or near those towns, which generated names must not copy. Best
// effort, like the English and Spanish lists.
export const REAL_AMERICAN_CLUB_NAMES = [
	"Atlanta United",
	"Austin FC",
	"Birmingham Legion",
	"Charleston Battery",
	"Charlotte FC",
	"Chattanooga FC",
	"Chicago Fire",
	"Colorado Rapids",
	"Columbus Crew",
	"D.C. United",
	"Detroit City",
	"FC Cincinnati",
	"FC Dallas",
	"FC Tulsa",
	"Hartford Athletic",
	"Houston Dynamo",
	"Indy Eleven",
	"Inter Miami",
	"LA Galaxy",
	"Las Vegas Lights",
	"Lexington SC",
	"Los Angeles FC",
	"Louisville City",
	"Memphis 901",
	"Miami FC",
	"Minnesota United",
	"Nashville SC",
	"New England Revolution",
	"New Mexico United",
	"New York City FC",
	"New York Red Bulls",
	"Oakland Roots",
	"Oklahoma City Energy",
	"Orlando City",
	"Philadelphia Union",
	"Phoenix Rising",
	"Pittsburgh Riverhounds",
	"Portland Timbers",
	"Real Salt Lake",
	"Richmond Kickers",
	"Rochester Rhinos",
	"Sacramento Republic",
	"San Antonio FC",
	"San Diego FC",
	"San Jose Earthquakes",
	"Seattle Sounders",
	"Spokane Velocity",
	"Sporting Kansas City",
	"St. Louis City",
	"Tampa Bay Rowdies",
	"Tulsa Athletic",
	"Union Omaha",
];

export const REAL_MEXICAN_CLUB_NAMES = [
	"Alebrijes de Oaxaca",
	"Atlante",
	"Atlas",
	"Atlético Morelia",
	"Atlético San Luis",
	"Cancún FC",
	"Celaya",
	"Club América",
	"Club Irapuato",
	"Club León",
	"Club Necaxa",
	"Club Puebla",
	"Club Tijuana",
	"Cruz Azul",
	"Deportivo Toluca",
	"Dorados de Sinaloa",
	"FC Juárez",
	"Guadalajara",
	"Mazatlán FC",
	"Monterrey",
	"Pachuca",
	"Querétaro FC",
	"Santos Laguna",
	"Tampico Madero",
	"Tepatitlán FC",
	"Tigres UANL",
	"Tlaxcala FC",
	"Toluca",
	"Veracruz",
	"Zacatepec",
];

export const REAL_ITALIAN_CLUB_NAMES = [
	"AC Milan",
	"AC Monza",
	"AC Perugia",
	"AC Reggiana",
	"AC Siena",
	"ACF Fiorentina",
	"Ancona",
	"Arezzo",
	"AS Roma",
	"Ascoli Calcio",
	"Atalanta",
	"Bari",
	"Benevento Calcio",
	"Bologna FC",
	"Brescia Calcio",
	"Cagliari Calcio",
	"Carrarese Calcio",
	"Catania FC",
	"Catanzaro",
	"Cesena FC",
	"Como 1907",
	"Cosenza Calcio",
	"Delfino Pescara",
	"Empoli FC",
	"Foggia",
	"Genoa CFC",
	"Hellas Verona",
	"Inter Milan",
	"Juventus",
	"Latina Calcio",
	"LR Vicenza",
	"Lucchese",
	"Messina",
	"Modena FC",
	"Novara FC",
	"Padova",
	"Palermo FC",
	"Parma Calcio",
	"Piacenza Calcio",
	"Pisa SC",
	"Pro Vercelli",
	"Reggina",
	"Rimini FC",
	"Salernitana",
	"Sampdoria",
	"Spal",
	"Spezia Calcio",
	"SS Lazio",
	"SSC Napoli",
	"Taranto",
	"Ternana Calcio",
	"Torino FC",
	"Trento Calcio",
	"Triestina",
	"Udinese Calcio",
	"US Avellino",
	"US Lecce",
	"US Livorno",
	"Venezia FC",
	"Virtus Verona",
];

export const REAL_GERMAN_CLUB_NAMES = [
	"1. FC Kaiserslautern",
	"1. FC Köln",
	"1. FC Magdeburg",
	"1. FC Nürnberg",
	"1. FC Saarbrücken",
	"1. FC Union Berlin",
	"Alemannia Aachen",
	"Arminia Bielefeld",
	"Bayer Leverkusen",
	"Bayern München",
	"Borussia Dortmund",
	"Borussia Mönchengladbach",
	"Borussia Gladbach",
	"Carl Zeiss Jena",
	"Chemnitzer FC",
	"Darmstadt 98",
	"Dynamo Dresden",
	"Eintracht Braunschweig",
	"Eintracht Frankfurt",
	"Energie Cottbus",
	"FC Augsburg",
	"FC Bayern München",
	"FC Erzgebirge Aue",
	"FC Ingolstadt",
	"FC Schalke 04",
	"FC St. Pauli",
	"Fortuna Düsseldorf",
	"Fortuna Köln",
	"Hallescher FC",
	"Hamburger SV",
	"Hannover 96",
	"Hansa Rostock",
	"Hertha Berlin",
	"Hertha BSC",
	"Holstein Kiel",
	"Karlsruher SC",
	"Kickers Offenbach",
	"KFC Uerdingen",
	"Lokomotive Leipzig",
	"MSV Duisburg",
	"Preußen Münster",
	"RB Leipzig",
	"Rot-Weiss Essen",
	"Rot-Weiß Erfurt",
	"Rot-Weiß Oberhausen",
	"SC Freiburg",
	"SC Paderborn",
	"SSV Jahn Regensburg",
	"SSV Ulm",
	"Stuttgarter Kickers",
	"SV Wehen Wiesbaden",
	"SV Werder Bremen",
	"TSV 1860 München",
	"VfB Lübeck",
	"VfB Oldenburg",
	"VfB Stuttgart",
	"VfL Bochum",
	"VfL Osnabrück",
	"VfL Wolfsburg",
	"Viktoria Köln",
	"Waldhof Mannheim",
	"Werder Bremen",
	"Wuppertaler SV",
	"Würzburger Kickers",
	"1. FSV Mainz 05",
	"FSV Mainz",
	"KSV Hessen Kassel",
	"SV Babelsberg",
];

export const REAL_JAPANESE_CLUB_NAMES = [
	"Albirex Niigata",
	"Avispa Fukuoka",
	"Blaublitz Akita",
	"Cerezo Osaka",
	"Consadole Sapporo",
	"FC Gifu",
	"FC Imabari",
	"FC Osaka",
	"FC Ryukyu",
	"FC Tokyo",
	"Fagiano Okayama",
	"Fukushima United",
	"Gainare Tottori",
	"Gamba Osaka",
	"Giravanz Kitakyushu",
	"Iwaki FC",
	"Jubilo Iwata",
	"Kagoshima United",
	"Kamatamare Sanuki",
	"Kataller Toyama",
	"Kawasaki Frontale",
	"Kochi United",
	"Kyoto Sanga",
	"Matsumoto Yamaga",
	"Mito HollyHock",
	"Montedio Yamagata",
	"Nagano Parceiro",
	"Nagoya Grampus",
	"Nara Club",
	"Oita Trinita",
	"Omiya Ardija",
	"Renofa Yamaguchi",
	"Roasso Kumamoto",
	"Sagamihara",
	"Sanfrecce Hiroshima",
	"Shimizu S-Pulse",
	"Tegevajaro Miyazaki",
	"Tokushima Vortis",
	"Tokyo Verdy",
	"Urawa Red Diamonds",
	"V-Varen Nagasaki",
	"Vanraure Hachinohe",
	"Vegalta Sendai",
	"Ventforet Kofu",
	"Vissel Kobe",
	"Yokohama F. Marinos",
	"Yokohama FC",
	"Zweigen Kanazawa",
	"Ehime FC",
	"Grulla Morioka",
];
